version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "10m"
    max-file: "3"

services:

  # api:
  #   build:
  #     context: .
  #     dockerfile: src/api/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   logging: *default-logging

  tg_bot:
    build:
      context: .
      dockerfile: src/bot/Dockerfile
    ports:
      - "8800:8800"
    env_file:
      - .env
    restart: unless-stopped
    logging: *default-logging

  scheduler:
    build:
      context: .
      dockerfile: src/scheduler/DockerFile
    env_file:
      - .env
    restart: unless-stopped
    logging: *default-logging

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=com_user
      - POSTGRES_PASSWORD=com265
      - POSTGRES_DB=random
    shm_size: 256mb
    ports:
      - 5656:5432
    volumes:
      - ./shared_data/pg_db:/var/lib/postgresql/data
    command: |
        postgres
          -c shared_preload_libraries=pg_stat_statements
          -c pg_stat_statements.track=all
          -c max_connections=1000
          -c shared_buffers=2GB
          -c effective_cache_size=8GB
          -c work_mem=64MB
          -c maintenance_work_mem=1GB
          -c min_wal_size=128MB
          -c max_wal_size=2GB
          -c checkpoint_completion_target=0.9
          -c wal_buffers=16MB
          -c default_statistics_target=100
    restart: unless-stopped