# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY src/scheduler/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project
COPY src/scheduler/ /app/
COPY database/ /app/database  
COPY utils_system/ /app/utils_system/   

# Command to run the application
CMD ["python", "runner.py"]
